name: lint and test

on:
  push:
    branches: ["*"]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: ["*"]
    paths-ignore:
      - '**/*.md'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  golangci:
    if: github.repository == 'twmb/franz-go'
    runs-on: ubuntu-latest
    name: "golangci-lint on amd64"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
